import Feladatok
#Feladatok.elsoFeladat()
#Feladatok.masodikFeladat(1231)
#Feladatok.harmadikFeladat(324)
#Feladatok.negyedikFeladat(0)
#Feladatok.otodikFeladat("Pentek","barmi")
#Feladatok.hatodikFeladat()
#Feladatok.hetedikFeladat()
#Feladatok.nyolcadikFeladat()
#Feladatok.kilencedikFeladat()
#Feladatok.tizedikFeladat()
#Feladatok.tizenegyesFeladat()
#Feladatok.tizenkettesFeladat()
#Feladatok.tizenharmasFeladat(21,120)
Feladatok.tizennegyesFeladat(412,243)